'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Namespace DevExpress.Example


    Partial Public Class UCOpenFile

        ''' <summary>
        ''' fileManager control.
        ''' </summary>
        ''' <remarks>
        ''' Auto-generated field.
        ''' To modify move field declaration from designer file to code-behind file.
        ''' </remarks>
        Protected fileManager As Global.DevExpress.Web.ASPxFileManager
    End Class
End Namespace
